#!/usr/bin/env bash
# Loops from 1 to 20 using while loop

i=1

while [ "$i" -le 20 ]; do
    case "$i" in
        4)
            echo "$i: Bad luck from China"
            ;;
        9)
            echo "$i: Bad luck from Japan"
            ;;
        17)
            echo "$i: Bad luck from Italy"
            ;;
        *)
            echo "$i: No bad luck"
            ;;
    esac
    ((i++))
done

