#!/bin/bash

# List files in the current directory in long format
echo "Current Directory:"
ls -l "$(dirname "$0")"

# List files in the parent directory of the working directory in long format
echo -e "\nParent Directory:"
ls -l "$(dirname "$0")/.."

# List files in the /boot directory in long format
echo -e "\n/boot Directory:"
ls -l /boot

